INSERT INTO ADDRESS (street, fk_planet)
VALUES ('Northfield', 16),
       ('Golf', 3),
       ('Sycamore', 16),
       ('Ludington', 16),
       ('Toban', 6),
       ('Steensland', 6),
       ('Reindahl', 18),
       ('Lakewood Gardens', 14),
       ('Bobwhite', 10),
       ('Johnson', 15),
       ('Reindahl', 3),
       ('Marquette', 8),
       ('Vermont', 1),
       ('Corscot', 13),
       ('2nd', 2),
       ('Waywood', 1),
       ('Tomscot', 9),
       ('Artisan', 2),
       ('Autumn Leaf', 16),
       ('Delaware', 8),
       ('Melvin', 8),
       ('Orin', 19),
       ('Morning', 18),
       ('East', 12),
       ('Stone Corner', 5),
       ('Morning', 9),
       ('Shasta', 10),
       ('Lawn', 17),
       ('Crowley', 13),
       ('Pleasure', 20),
       ('Vera', 20),
       ('Lighthouse Bay', 12),
       ('Rusk', 8),
       ('Morning', 2),
       ('Hollow Ridge', 4),
       ('Weeping Birch', 12),
       ('Ludington', 13),
       ('Carpenter', 4),
       ('Melby', 17),
       ('Esker', 14),
       ('Eliot', 17),
       ('Express', 15),
       ('Vahlen', 8),
       ('Buhler', 13),
       ('Eagle Crest', 8),
       ('Pine View', 10),
       ('Dovetail', 6),
       ('Old Shore', 9),
       ('Clove', 13),
       ('Golf View', 19),
       ('Maywood', 5),
       ('Birchwood', 2),
       ('Emmet', 6),
       ('Havey', 6),
       ('Vidon', 20),
       ('Vidon', 19),
       ('Moose', 9),
       ('Hintze', 18),
       ('Oak Valley', 10),
       ('Sundown', 1),
       ('Debra', 18),
       ('Tennyson', 9),
       ('Novick', 8),
       ('Gateway', 10),
       ('Stoughton', 20),
       ('Merrick', 9),
       ('Maywood', 12),
       ('Aberg', 7),
       ('High Crossing', 6),
       ('Declaration', 14),
       ('Vidon', 8),
       ('Mcguire', 11),
       ('Saint Paul', 7),
       ('Corben', 17),
       ('Dovetail', 19),
       ('Hallows', 12),
       ('Coolidge', 19),
       ('Ilene', 6),
       ('Bunker Hill', 8),
       ('Meadow Vale', 8),
       ('Crowley', 12),
       ('8th', 18),
       ('Service', 5),
       ('Redwing', 9),
       ('Norway Maple', 12),
       ('Hallows', 2),
       ('Drewry', 7),
       ('Loeprich', 18),
       ('Barnett', 7),
       ('Commercial', 11),
       ('Rigney', 5),
       ('Sage', 8),
       ('Loomis', 16),
       ('Bluejay', 19),
       ('Anderson', 7),
       ('Eliot', 4),
       ('Bluejay', 20),
       ('Paget', 4),
       ('Westport', 12),
       ('Ramsey', 3),
       ('Manitowish', 15),
       ('Fairview', 4),
       ('Esch', 2),
       ('Banding', 15),
       ('Ridgeway', 8),
       ('Warrior', 20),
       ('Lunder', 19),
       ('Coleman', 12),
       ('Kipling', 15),
       ('Ridgeview', 6),
       ('Commercial', 17),
       ('Maryland', 1),
       ('Buena Vista', 12),
       ('Nancy', 8),
       ('Paget', 12),
       ('Grayhawk', 5),
       ('Carioca', 6),
       ('Waywood', 1),
       ('Duke', 9),
       ('Hoepker', 10),
       ('Grover', 4),
       ('Forest', 11),
       ('Sutherland', 16),
       ('Jenifer', 10),
       ('Reindahl', 11),
       ('Crescent Oaks', 13),
       ('Grim', 5),
       ('Stuart', 7),
       ('Becker', 12),
       ('Upham', 8),
       ('Amoth', 16),
       ('Pennsylvania', 6),
       ('Sugar', 12),
       ('Pine View', 19),
       ('Kipling', 3),
       ('Pine View', 17),
       ('Menomonie', 7),
       ('Prairieview', 10),
       ('Emmet', 20),
       ('Pleasure', 14),
       ('Orin', 18),
       ('Oneill', 18),
       ('7th', 7),
       ('Warner', 20),
       ('Maryland', 20),
       ('Almo', 3),
       ('Corry', 9),
       ('Village', 7),
       ('Boyd', 3),
       ('Red Cloud', 4),
       ('Cherokee', 17),
       ('Burrows', 19),
       ('Ilene', 1),
       ('Bunker Hill', 2),
       ('Talmadge', 6),
       ('Northland', 8),
       ('Randy', 13),
       ('Mallory', 8),
       ('Fairfield', 1),
       ('Tennyson', 12),
       ('Moose', 10),
       ('Carey', 1),
       ('Weeping Birch', 4),
       ('Burning Wood', 13),
       ('Springview', 8),
       ('Bunker Hill', 14),
       ('Elgar', 9),
       ('Truax', 8),
       ('Bashford', 11),
       ('Granby', 10),
       ('Fallview', 11),
       ('Oak Valley', 4),
       ('Division', 3),
       ('Fair Oaks', 11),
       ('Anthes', 6),
       ('Jenna', 12),
       ('Derek', 6),
       ('Hermina', 3),
       ('Amoth', 15),
       ('Browning', 10),
       ('Blue Bill Park', 17),
       ('Waywood', 11),
       ('International', 15),
       ('Westport', 3),
       ('Glendale', 7),
       ('Talmadge', 6),
       ('Michigan', 7),
       ('Menomonie', 11),
       ('Daystar', 4),
       ('Ruskin', 19),
       ('Straubel', 7),
       ('Ramsey', 4),
       ('Twin Pines', 15),
       ('Arizona', 16),
       ('Cottonwood', 4),
       ('Coleman', 16),
       ('Elmside', 20),
       ('Colorado', 6),
       ('Buhler', 9),
       ('4th', 11),
       ('American', 18),
       ('Gulseth', 14),
       ('American Ash', 14),
       ('Hallows', 20),
       ('Vahlen', 6),
       ('Huxley', 14),
       ('Hazelcrest', 9),
       ('Kings', 7),
       ('Atwood', 19),
       ('Lakeland', 18),
       ('Grim', 12),
       ('Hintze', 8),
       ('Anzinger', 9),
       ('Schlimgen', 4),
       ('Melvin', 4),
       ('Monica', 20),
       ('Derek', 1),
       ('Mendota', 5),
       ('Ridgeview', 17),
       ('Russell', 6),
       ('Forster', 19),
       ('Redwing', 10),
       ('Longview', 10),
       ('Ryan', 2),
       ('Erie', 12),
       ('Namekagon', 8),
       ('Vahlen', 5),
       ('Scott', 14),
       ('Northview', 2),
       ('Buhler', 1),
       ('Ronald Regan', 15),
       ('Mayer', 15),
       ('Redwing', 3),
       ('Londonderry', 20),
       ('1st', 20),
       ('Elka', 15),
       ('Waxwing', 18),
       ('Texas', 4),
       ('Division', 18),
       ('Texas', 5),
       ('Grayhawk', 11),
       ('Bluestem', 17),
       ('Corry', 14),
       ('Prentice', 20),
       ('Lighthouse Bay', 11),
       ('Meadow Valley', 8),
       ('Amoth', 4),
       ('Eliot', 11),
       ('Hoard', 3),
       ('Rowland', 3),
       ('Colorado', 18),
       ('Harper', 9),
       ('Elgar', 10),
       ('Maywood', 10),
       ('Melrose', 1),
       ('Dakota', 13),
       ('Duke', 7),
       ('Buhler', 19),
       ('Mockingbird', 13),
       ('Esch', 16),
       ('Starling', 11),
       ('Vernon', 11),
       ('Moland', 4),
       ('Becker', 3),
       ('Swallow', 1),
       ('Meadow Valley', 16),
       ('American', 17),
       ('Kingsford', 12),
       ('Northland', 2),
       ('Elka', 2),
       ('Pierstorff', 1),
       ('Dryden', 17),
       ('Carberry', 15),
       ('Northwestern', 12),
       ('Summer Ridge', 15),
       ('Grim', 10),
       ('Dryden', 3),
       ('Eagle Crest', 20),
       ('Fisk', 5),
       ('Fordem', 5),
       ('Randy', 16),
       ('Grover', 10),
       ('Mockingbird', 19),
       ('Red Cloud', 16),
       ('Golf', 3),
       ('Kensington', 10),
       ('Carioca', 3),
       ('Straubel', 1),
       ('Sauthoff', 1),
       ('Beilfuss', 14),
       ('Valley Edge', 3),
       ('Barby', 20),
       ('Shasta', 10),
       ('Onsgard', 14),
       ('Dakota', 5),
       ('Debra', 2),
       ('Miller', 12),
       ('Green', 6),
       ('Hermina', 11),
       ('Rutledge', 17),
       ('Dovetail', 1),
       ('Mayer', 6),
       ('Montana', 11),
       ('Banding', 6),
       ('Buell', 18),
       ('Macpherson', 11),
       ('Mitchell', 15),
       ('Carioca', 3),
       ('Ilene', 7),
       ('Dexter', 2),
       ('Raven', 4),
       ('Vahlen', 11),
       ('Hollow Ridge', 14),
       ('Longview', 9),
       ('Mcbride', 17),
       ('Straubel', 12),
       ('Calypso', 14),
       ('Jenifer', 19),
       ('Erie', 3),
       ('South', 13),
       ('Melrose', 11),
       ('Rigney', 13),
       ('Knutson', 13),
       ('Green', 17),
       ('Kensington', 20),
       ('Nevada', 8),
       ('Erie', 10),
       ('Pleasure', 20),
       ('Schlimgen', 8),
       ('Heath', 7),
       ('Riverside', 4),
       ('Starling', 10),
       ('Prentice', 8),
       ('Northridge', 20),
       ('Kings', 9),
       ('New Castle', 2),
       ('Schlimgen', 17),
       ('Vahlen', 14),
       ('Shopko', 7),
       ('Dawn', 7),
       ('Talisman', 11),
       ('Merrick', 20),
       ('Rowland', 4),
       ('Blue Bill Park', 1),
       ('Warner', 17),
       ('Brown', 5),
       ('Crowley', 3),
       ('Northview', 5),
       ('Orin', 4),
       ('Erie', 20),
       ('Emmet', 18),
       ('Gina', 17),
       ('North', 11),
       ('Sundown', 18),
       ('Iowa', 19),
       ('Commercial', 11),
       ('Lotheville', 18),
       ('Thackeray', 3),
       ('Westport', 1),
       ('Warner', 15),
       ('Bay', 14),
       ('8th', 17),
       ('Ruskin', 3),
       ('Banding', 18),
       ('Nobel', 8),
       ('Acker', 11),
       ('Morrow', 2),
       ('Londonderry', 9),
       ('Russell', 20),
       ('Everett', 13),
       ('Haas', 8),
       ('Morrow', 2),
       ('Stoughton', 12),
       ('Glacier Hill', 13),
       ('Vidon', 2),
       ('Summerview', 17),
       ('Browning', 15),
       ('Boyd', 9),
       ('Ludington', 9),
       ('North', 13),
       ('Maywood', 16),
       ('Parkside', 14),
       ('Westridge', 12),
       ('Bunker Hill', 15),
       ('Fremont', 17),
       ('Glendale', 6),
       ('Thackeray', 4),
       ('Lyons', 15),
       ('5th', 6),
       ('Mendota', 5),
       ('Twin Pines', 6),
       ('6th', 1),
       ('Hoffman', 6),
       ('Summer Ridge', 20),
       ('Del Sol', 7),
       ('Jana', 12),
       ('Cambridge', 20),
       ('Westport', 6),
       ('Onsgard', 5),
       ('Jenna', 20),
       ('Onsgard', 5),
       ('Sundown', 7),
       ('Center', 17),
       ('Anhalt', 5),
       ('Loftsgordon', 11),
       ('Starling', 5),
       ('Valley Edge', 6),
       ('Blaine', 13),
       ('Burning Wood', 14),
       ('Kensington', 6),
       ('Fuller', 18),
       ('Buhler', 5),
       ('Kenwood', 3),
       ('Cody', 7),
       ('Veith', 4),
       ('Division', 5),
       ('Esch', 7),
       ('Troy', 1),
       ('Gerald', 1),
       ('Ridge Oak', 12),
       ('Petterle', 5),
       ('5th', 20),
       ('Harbort', 14),
       ('Dennis', 5),
       ('Anthes', 10),
       ('Victoria', 12),
       ('Manley', 13),
       ('Pearson', 11),
       ('Scott', 16),
       ('Carpenter', 11),
       ('Anniversary', 17),
       ('Eliot', 1),
       ('Miller', 3),
       ('Carioca', 14),
       ('Grim', 15),
       ('Dahle', 3),
       ('Old Shore', 17),
       ('Becker', 2),
       ('Namekagon', 3),
       ('Mockingbird', 18),
       ('Maple Wood', 5),
       ('Judy', 18),
       ('Scofield', 19),
       ('Myrtle', 13),
       ('Elmside', 2),
       ('Linden', 18),
       ('Sauthoff', 3),
       ('Westend', 5),
       ('Fordem', 9),
       ('Crownhardt', 20),
       ('6th', 16),
       ('Spenser', 11),
       ('6th', 16),
       ('Di Loreto', 12),
       ('Ronald Regan', 19),
       ('Esker', 12),
       ('Basil', 12),
       ('Dottie', 7),
       ('Dunning', 15),
       ('Montana', 6),
       ('Stuart', 5),
       ('Vahlen', 10),
       ('Kinsman', 10),
       ('Bunker Hill', 2),
       ('Homewood', 19),
       ('Northwestern', 1),
       ('Karstens', 1),
       ('Norway Maple', 5),
       ('West', 16),
       ('Swallow', 18),
       ('Sunbrook', 3),
       ('Doe Crossing', 5),
       ('Talisman', 13),
       ('Rigney', 7),
       ('Golf', 11),
       ('David', 13),
       ('Colorado', 11),
       ('Merchant', 8),
       ('Division', 14),
       ('Forest', 20),
       ('Union', 2),
       ('Crownhardt', 20),
       ('Waxwing', 1),
       ('Raven', 5),
       ('Summit', 10),
       ('Fairview', 7),
       ('Forster', 11),
       ('Surrey', 15),
       ('Ohio', 10),
       ('Towne', 15),
       ('Rutledge', 14),
       ('Clove', 8),
       ('Calypso', 8),
       ('Longview', 9),
       ('Sachs', 5),
       ('Eggendart', 14),
       ('Arkansas', 6),
       ('Mallory', 10),
       ('Trailsway', 6),
       ('Summer Ridge', 16),
       ('Forest Dale', 12),
       ('Manufacturers', 19),
       ('1st', 6),
       ('Pawling', 4),
       ('Petterle', 6),
       ('Gulseth', 10),
       ('Dexter', 6),
       ('Haas', 18),
       ('Grover', 18),
       ('Eagle Crest', 1),
       ('Haas', 19),
       ('Springs', 17),
       ('Prairie Rose', 16),
       ('Chinook', 1),
       ('Blue Bill Park', 12),
       ('Barby', 3),
       ('Coleman', 14),
       ('Banding', 1),
       ('Lake View', 9),
       ('Pawling', 5),
       ('Westridge', 9),
       ('Homewood', 19),
       ('Harbort', 5),
       ('Lawn', 3),
       ('Barnett', 16),
       ('Thompson', 6),
       ('Monica', 6),
       ('Glacier Hill', 3),
       ('Ryan', 6),
       ('Arizona', 8),
       ('Lukken', 9),
       ('Amoth', 1),
       ('Dryden', 11),
       ('Huxley', 6),
       ('Sherman', 2),
       ('Dottie', 16),
       ('Loomis', 15),
       ('Porter', 1),
       ('Thierer', 2),
       ('Buell', 16),
       ('Messerschmidt', 9),
       ('Park Meadow', 17),
       ('Elka', 9),
       ('Old Gate', 19),
       ('Ridgeview', 6),
       ('Hintze', 7),
       ('Surrey', 10),
       ('Summer Ridge', 13),
       ('Mariners Cove', 18),
       ('Fair Oaks', 15),
       ('Judy', 3),
       ('Texas', 20),
       ('Farragut', 8),
       ('Oxford', 7),
       ('Atwood', 13),
       ('Green', 3),
       ('Farmco', 12),
       ('Sullivan', 18),
       ('Shopko', 15),
       ('Westend', 12),
       ('Crowley', 20),
       ('Donald', 17),
       ('Columbus', 1),
       ('Novick', 9),
       ('Dakota', 17),
       ('Center', 11),
       ('3rd', 9),
       ('Packers', 19),
       ('Oxford', 9),
       ('Briar Crest', 20);
