INSERT INTO SPACEPORT (name, fk_address)
VALUES ('Lindi', 1),
       ('Komoro', 2),
       ('Cigenca', 3),
       ('Arruda dos Vinhos', 4),
       ('Périgueux', 5),
       ('Radvanice', 6),
       ('Rancakole', 7),
       ('Lyon', 8),
       ('Randuagung', 9),
       ('Pirané', 10),
       ('Nong Hi', 11),
       ('Fale old settlement', 12),
       ('Socorro', 13),
       ('San Antonio', 14),
       ('Granada', 15),
       ('Yinhedahan’er', 16),
       ('Cuntan', 17),
       ('Florencio Varela', 18),
       ('Udanin', 19),
       ('Guadalupe', 20),
       ('Nyandoma', 21),
       ('Gbarnga', 22),
       ('Plovdiv', 23),
       ('Nos Astra', 24),
       ('La Esperanza', 25),
       ('Usman’', 26),
       ('Cancela', 27),
       ('Shankill', 28),
       ('Samparna', 29),
       ('Skála Oropoú', 30),
       ('Sangiang', 31),
       ('Srokowo', 32),
       ('Gaoshibei', 33),
       ('Kaiyuan', 34),
       ('Sapele', 35),
       ('Bakersfield', 36),
       ('San Gil', 37),
       ('Matalam', 38),
       ('Bor', 39),
       ('Sidem', 40),
       ('Kuroiso', 41),
       ('Fayzabad', 42),
       ('Traiguén', 43),
       ('Lefkímmi', 44),
       ('Minneapolis', 45),
       ('Yashikera', 46),
       ('Uromi', 47),
       ('Corroios', 48),
       ('Matriz de Camaragibe', 49),
       ('Qŭrghonteppa', 50);
