INSERT INTO PLANET (name)
VALUES ('Citadel'),
       ('Earth'),
       ('Luna'),
       ('Mars'),
       ('Terra Nova'),
       ('Eden Prime'),
       ('Akuze'),
       ('Horizon'),
       ('Feros'),
       ('Freedom''s Progress'),
       ('Thessia'),
       ('Illium'),
       ('Palaven'),
       ('Menae'),
       ('Sur''Kesh'),
       ('Tuchanka'),
       ('Rannoch'),
       ('Noveria'),
       ('Dekuuna'),
       ('Omega');
