INSERT INTO CORPORATION (name, fk_address)
VALUES ('Metz, Borer and Hahn', 1),
       ('Corkery Group', 2),
       ('Hilpert, Renner and Bradtke', 3),
       ('Wolff and Sons', 4),
       ('Rippin LLC', 5),
       ('Erdman and Sons', 6),
       ('Eichmann and Sons', 7),
       ('Bogan, Braun and Veum', 8),
       ('Quigley, Konopelski and Little', 9),
       ('Watsica-Leffler', 10),
       ('Bogan-Marvin', 11),
       ('Conroy, Maggio and Russel', 12),
       ('Jacobs-Towne', 13),
       ('Barton LLC', 14),
       ('Shanahan, Bernier and Cummerata', 15),
       ('Cruickshank LLC', 16),
       ('Stamm Group', 17),
       ('Cummerata and Sons', 18),
       ('Rutherford LLC', 19),
       ('VonRueden Group', 20);
